apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rahulpatrajee1/connectrabackend:13eb3716b5681344f121d2b6d1bd071906f0fd11
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: backend-secret


---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: LoadBalancer